### ISSUE TITLE
UnavailableDataError: Key 'b'COUNTERS_PORT_NAME_MAP'' unavailable in database 'COUNTERS_DB'

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-snmpagent#28]
this error could be caught and handled better:
```
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent Traceback (most recent call last):
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     "__main__", mod_spec)
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     exec(code, run_globals)
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/__main__.py", line 74, in <module>
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     from .main import main
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/main.py", line 12, in <module>
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     from sonic_ax_impl.mibs import ieee802_1ab
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 99, in <module>
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     _lldp_updater = LLDPUpdater()
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 34, in __init__
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     self.reinit_data()
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 50, in reinit_data
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     self.oid_name_map = mibs.init_sync_d_interface_tables(self.db_conn)
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/__init__.py", line 104, in init_sync_d_interface_tables
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     if_name_map = db_conn.get_all(COUNTERS_DB, COUNTERS_PORT_NAME_MAP, blocking=True)
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     ret_data = f(inst, db_name, *args, **kwargs)
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent   File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 303, in get_all
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent     raise UnavailableDataError(message, _hash)
Jun  5 22:14:48.0 str-a7050-acs-1 INFO supervisord: snmp-subagent swsssdk.exceptions.UnavailableDataError: Key 'b'COUNTERS_PORT_NAME_MAP'' unavailable in database 'COUNTERS_DB'
```

**Comment by tieguoevan** [comment]
Will it cause snmp_interfaces test failure?

**Comment by stcheng** [comment]
yes. i think it is already fixed. please check.

**Comment by LeonardZhan** [comment]
How is it solved? I have the same problem now
