### ISSUE TITLE
UnavailableDataError for Key "COUNTERS_PORT_NAME_MAP" in COUNTERS_DB

### ISSUE THREAD

**Issue by sripalnati** [Azure/sonic-snmpagent#84]
Aug 31 20:27:22.308214 switch75 ALERT pmon/sensord: Sensor alarm: Chip max1617a-i2c-40-2a: ASIC: -5.0 C (min = -5.0 C, max = -5.0 C) [ALARM]
Aug 31 20:27:44.565279 switch75 ERR snmp/snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 38, in reinit_data#012    self.oid_name_map = mibs.init_sync_d_interface_tables(self.db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/__init__.py", line 88, in init_sync_d_interface_tables#012    if_name_map, if_id_map = port_util.get_interface_oid_map(db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/port_util.py", line 40, in get_interface_oid_map#012    if_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_PORT_NAME_MAP', blocking=True)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped#012    ret_data = f(inst, db_name, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 310, in get_all#012    raise UnavailableDataError(message, _hash)#012swsssdk.exceptions.UnavailableDataError: Key 'COUNTERS_PORT_NAME_MAP' unavailable in database 'COUNTERS_DB'

**Comment by jerry-chang3300** [comment]
We have similar error log as previous, it seems that SNMP tries to get queue_stat_map before it's created.   Since SNMP would retry to get it again, it should not be a problem, so we low down the log level from error to warning.

```
"Oct 5 06:26:20.005020 as7816-64x ERR snmp#snmp-subagent [sonic_ax_impl] ERROR: No queue stat counters found in the Counter DB. SyncD database is incoherent.",
"Oct 5 06:26:20.006722 as7816-64x ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012 File \"/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py\", line 40, in start#012 self.reinit_data()#012 File \"/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py\", line 79, in reinit_data#012 mibs.init_sync_d_queue_tables(self.db_conn)#012 File \"/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/_init_.py\", line 332, in init_sync_d_queue_tables#012 raise RuntimeError('The queue_stat_map is not defined')#012RuntimeError: The queue_stat_map is not defined",
```

**Comment by jerry-chang3300** [comment]
The root cause should be the difference in time between containers.  
PortOrch would write QUEUE_COUNTER_ID_LIST to Flex_Counter_DB when initialize, and SyncD_Flex_Counter would write counter to Counter_DB after it collects counter.  
But SNMP may query Counter_DB by QUEUE_COUNTER_ID_LIST before SyncD_Flex_Counter write counters to Counter_DB, then SNMP can't get it and write this log.
